name: arm-runner-action

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2
      with:
        commands: uname -a
    - uses: pguyot/arm-runner-action@v2
      with:
        commands: docker build . --file Dockerfile
                
