name: Docker Image CI

on:
  push:
    branches: [ master ]


jobs:
  try_macos:
    runs-on: macos-latest
    container:
      image: ubuntu
      
    steps:
    - name: show vars
      run: |
            env 
            ls -la
            pwd

#   build_using_qus:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - uses: dbhi/qus/action@main
#       with:
#         targets: arm
#     - name: Build the Docker arm image
#       run: docker build . --file Dockerfile.arm --tag arm-image:$(date +%s)

#   build_using_arm-runner-action:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: pguyot/arm-runner-action@v2
#       with:
#         commands: uname -a
#     - uses: pguyot/arm-runner-action@v2
#       with:
#         commands: | 
#           uname -a && \
#           apt update && apt-get install -y \
#                           automake build-essential git libbsd-dev libedit-dev \
#                           libevent-dev libgmp-dev libgmpxx4ldbl libpcre3-dev \
#                           libssl-dev libtool libxml2-dev libyaml-dev \
#                           lld llvm llvm-dev && \
#           git clone -b v8.0.6 https://github.com/ivmai/bdwgc.git && \
#           cd bdwgc && \
#           git clone https://github.com/ivmai/libatomic_ops.git && \
#           ./autogen.sh && \
#           ./configure --disable-debug --disable-shared --enable-large-config && \
#           make -j && \
#           make check && \ 
#           make install

