name: Docker Image CI

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - uses: dbhi/qus/action@main
      with:
        targets: arm aarch64
    - name: Build the Docker arm image
      run: docker build . --file Dockerfile.arm --tag arm-image:$(date +%s)
